pipeline {
    agent any
    tools { maven 'Maven3' }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
        stage('Docker Build & Deploy') {
            steps {
                sh 'docker build -t simple-java-maven-app:latest .'
                sh 'docker run -d -p 8080:8080 simple-java-maven-app:latest'
            }
        }
    }
}
